local _, ADDON = ...

ADDON.Category = {
    ["Hearthstone"] = 1,
}

ADDON.db = {
    {["toy"] = 54452, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 64488, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 93672, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 110560, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 140192, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 142542, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 162973, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 163045, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 165669, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 165670, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 165802, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 166746, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 166747, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 168907, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 172179, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 180290, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 182773, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 183716, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 184353, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 184871, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 188952, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 190196, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 190237, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 193588, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 200630, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 206195, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 209035, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 208704, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 210455, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 212337, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 228940, ["category"] = ADDON.Category.Hearthstone},
    {["toy"] = 235016, ["category"] = ADDON.Category.Hearthstone},
}